name: hair

on:
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        run: echo "Checkout Done"
      
      - name: Set Up Java 11
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
      
      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_BACK_USERNAME }}
          password: ${{ secrets.DOCKERHUB_BACK_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: true
          tags: latest
